// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ADoption: typeof import('@arco-design/web-vue')['Doption']
    ADropdown: typeof import('@arco-design/web-vue')['Dropdown']
    ASwitch: typeof import('@arco-design/web-vue')['Switch']
    ATypographyText: typeof import('@arco-design/web-vue')['TypographyText']
  }
}

export { }
