Server:
#  debug release
  RenMode: debug
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
Database:
  DBtype: mysql
  UserName: root
  Password:
  Host: localhost:3306
  DBName: gin_react_admin
  TablePrefix: blog_
  Charset: utf8
  ParseTime: true
  MaxIdleConns: 10
  MaxOpenConns: 30
Captcha:
  ImgWidth: 110
  ImgHeight: 40
  KeyLong: 4
  MaxSkew: 0.4
  DotCount: 40
JWT:
  Issuer: gin_react_admin
  SigningKey: "zhaozunhong..3132"
  ExpiresAt: 7
  BufferTime: 2
FileService:
  UploadPath: "assets/upload"
  StaticPath: "./assets"
  HashKey: "abcd"